import Link from 'next/link';
import { Button, Card } from '@/components/ui';
import { InviteCard, ParticipantList, VotingProgress } from './room-components';
import { mockResult, mockRoom } from './mock-room';

export function LobbyScreen() { return <div className="stack"><section className="page-intro"><span className="status-pill"><span className="status-dot" />Lobby</span><h1 className="room-title">{mockRoom.session.title}</h1><p className="lede">Pick a place everyone can live with. Invite the crew, then start when they’re ready.</p></section><InviteCard /><Card><div className="split"><div><h2>People in this room</h2><p className="muted">Readiness is shared. Votes won’t be.</p></div><span className="muted">{mockRoom.participants.length} people</span></div><ParticipantList /></Card><Card><h2>Options</h2>{mockRoom.session.options.map((option) => <div className="option-line" key={option.id}><span className="option-number">{option.order + 1}</span><strong>{option.label}</strong></div>)}</Card><div className="row"><Link href={`/room/${mockRoom.session.id}/vote`}><Button>Vote privately</Button></Link><Link href={`/room/${mockRoom.session.id}/result`}><Button variant="quiet">Preview result</Button></Link></div></div>; }

export function ResultScreen() { const winner = mockRoom.session.options.find((option) => option.id === mockResult.winnerOptionId)!; return <div className="stack"><section className="page-intro"><p className="eyebrow">Decision complete</p><h1 className="room-title">A plan everyone can live with.</h1></section><Card className="winner"><p className="eyebrow" style={{ color: 'white' }}>Tonight’s pick</p><h2>{winner.label}</h2><p>Best Fit · group-ready choice</p></Card><Card><h2>Why this won</h2><div className="result-why"><p>{mockResult.explanation}</p><p className="muted" style={{ marginBottom: 0, fontSize: '.85rem' }}>This is an aggregate explanation — it does not reveal anyone’s ballot or veto.</p></div></Card><Card className="backup"><h2>Backup option</h2><p><strong>{mockRoom.session.options[1]!.label}</strong> is ready if the plan changes.</p></Card><VotingProgress finished={3} total={3} /><Card><h2>Make it happen</h2><p className="muted">These actions are presentation-only in this mock.</p><div className="row"><Button>Share plan</Button><Button variant="secondary">Open directions</Button></div></Card></div>; }

export function RoomState({ kind }: { kind: 'loading' | 'error' | 'disconnected' | 'empty' }) { const content = { loading: ['Setting up your room', 'Your room details are loading.'], error: ['We could not load this room', 'Nothing has been changed. Try again when you’re ready.'], disconnected: ['Reconnecting to the room', 'We’ll refresh shared readiness and progress when connection returns.'], empty: ['No decision options yet', 'Add at least two options before inviting the group.'] }[kind]; return <Card className="state-panel"><div>{kind === 'loading' && <div className="skeleton" aria-hidden="true" />}<h1 className="room-title" role={kind === 'loading' ? 'status' : undefined}>{content[0]}</h1><p className="muted">{content[1]}</p>{kind !== 'loading' && <Button>{kind === 'empty' ? 'Add an option' : 'Try again'}</Button>}</div></Card>; }
